ALTER INDEX IF EXISTS public.idx_Assignment_Discriminator_Performer_Author_MainTask_Com_etc0 RENAME TO idx_Asg_Discriminator_Performer_Author_MTask_ComplBy_Created;
ALTER INDEX IF EXISTS public.idx_ElectronicDocument_Discriminator_Created_LifeCycleState RENAME TO idx_EDoc_Discriminator_Created_LifeCycleState;
ALTER INDEX IF EXISTS public.idx_ElectronicDocument_Discriminator_RegState_RegDate_RegNu_etc RENAME TO idx_EDoc_Discriminator_RegState_RegDate_RegNumber_Created;
ALTER INDEX IF EXISTS public.idx_ElectronicDocument_Index_DocRegister_Id_Discriminator RENAME TO idx_EDoc_Index_DocRegister_Id_Discriminator;
ALTER INDEX IF EXISTS public.Sungero_DocRegister_CurrentCode_DocRegisterId_Month_Year_LeadDo RENAME TO Sungero_DocRegister_CurrentCode_DocRegisterId_Month_Year_LDoc;
